name: Deploy VitePress site to Pages

on:
  # push:
  #   branches: [master] # Configurado para tu rama master
  workflow_dispatch: # Permite ejecutarlo manualmente desde la pestaña Actions

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 20
          # Quitamos el cache temporalmente hasta que tengas un package-lock.json

      - name: Install dependencies
        run: |
          if [ ! -f package.json ]; then npm init -y; fi
          npm install -D vitepress vue

