name: Deploy VitePress site to Pages

on:
  workflow_dispatch:
  # push:
  #   branches: [main] # Cambiá a 'master' si tu rama principal se llama así

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm add -D vitepress vue
      - name: Build with VitePress
        run: npx vitepress build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: .vitepress/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
